### ISSUE TITLE
Add: Hyphenation

### ISSUE THREAD

**Issue by minthemiddle** [CodeDesignInitiative/cdweb1801#102]
- Long text would look a lot better if words would break at the right place automatically (= hyphenation)
- `hyphens: auto;` works pretty well – just [not at Chrome Windows (yet)](https://caniuse.com/#feat=css-hyphens)
- As we do not have a custom (S)CSS workflow yet, the preferred solution would be to change the master template (`layouts/master.blade.php`), where hyphens are already defined as `.hyphens`:

```css
.hyphens {
  -webkit-hyphens: auto;
  -moz-hyphens: auto;
  hyphens: auto;
}
```
